# Hilltop Server Configuration
base_url: "http://hilltopdev.horizons.govt.nz/"
hts: "boo.hts"
export_file: "output_dump/missing.csv"
start: "2024-04-01 00:00"
end: "2024-05-01 00:00"

sites:
    - "344187"
    - "344189"
    - "344222"
    - "354021"
    - "354070"
    - "362486"
    - "362487"
    - "362488"
    - "362489"
    - "362490"
    - "362492"
    - "362493"
    - "362494"
    - "362495"
    - "362496"
    - "362497"
    - "362498"
    - "362499"
    - "362500"
    - "362502"
    - "362503"
    - "362504"
    - "362505"
    - "ATH-2008012389"
    - "Ahuahu at Te Tuhi Junction"
    - "Air Quality at Taihape"
    - "Air Quality at Taumarunui"
    - "Akitio at Cadmus Bridge"
    - "Akitio at Toi Flat"
    - "Akitio at Weber"
    - "Amons"
    - "Arawhata Drain at Dairy Track Bridge"
    - "Arawhata Drain at Dairy Track Sump"
    - "Arawhata Drain at Hokio Beach Road"
    - "Arawhata Drain at Kane Farm"
    - "Arawhata at Culvert ds Joblins"
    - "Arawhata at us Hokio Beach Road"
    - "Burkes Drain at Hockly Bridge"
    - "Butlers"
    - "Desert Rd Summit Climate Station"
    - "Forest Rd Drain at Drop Structure"
    - "HDC Foxton Beach 1"
    - "HDC Foxton Beach 3"
    - "HDC Stormwater at Fairfield Rd"
    - "Hautapu at Alabasters"
    - "Hautapu at Mounganui Station"
    - "Hokio at Lake Horowhenua"
    - "Hokowhitu Lagoon at Pump Shed"
    - "Hyde Park Bore 2"
    - "Joblins at Kane Boundary"
    - "KB Drain at Gillespies Line"
    - "Kahuterawa at Johnstons Rata"
    - "Kahuterawa at Scotts Road"
    - "Kai Iwi at Handley Road"
    - "Kawhatau Catchment at Upper Kawhatau"
    - "Kawhatau at Parenga"
    - "Kawhatau at Potaka Bridge"
    - "Kings Canal at Cook Street"
    - "Kiwitea at Strathspey Farm"
    - "Koitiata at Beamish Rd"
    - "Koputaroa at Tavistock Rd"
    - "Kuku Beach"
    - "Kumeti at Rua Roa"
    - "Kumeti at Te Rehunga"
    - "L Horowhenua Inflow at Lindsay Road"
    - "Lake Dudding"
    - "Lake Heaton"
    - "Lake Herbert"
    - "Lake Horowhenua at Buoy"
    - "Lake Horowhenua at Weed Buoy 1"
    - "Lake Horowhenua at Weed Buoy 2"
    - "Lake Horowhenua at Weir"
    - "Lake Kohata"
    - "Lake Koitiata"
    - "Lake Papaitonga at Staff Gauge"
    - "Lake Pauri"
    - "Lake William"
    - "Lake Wiritoa"
    - "Linton Drain at Tane Road"
    - "Lower Retaruke"
    - "MDC Himatangi Shallow"
    - "Main Drain at Lynchs Bridge"
    - "Main Drain at Rangiotu Gates"
    - "Makahiwi at Repeater"
    - "Makakahi at Hamua"
    - "Makino Floodway at Gate 1"
    - "Makino Floodway at Gate 2"
    - "Makino Floodway at Gate 3"
    - "Makino Floodway at Gate 4"
    - "Makino Floodway at Gate 5"
    - "Makino at Boness Road"
    - "Makino at Cheltenham"
    - "Makino at Duke St"
    - "Makino at Floodgates"
    - "Makino at Halcombe Road"
    - "Makino at Makino Farm"
    - "Makino at Rata Street"
    - "Makino at Reids Line"
    - "Makohine at Zohs Road"
    - "Makotuku at F Trig"
    - "Makotuku at Raetihi"
    - "Makotuku at SH49A"
    - "Makowhai Tributary at SH1"
    - "Makowhai at SH1"
    - "Makowhai at ds Ohakea"
    - "Makuri at Bee 4 Trig"
    - "Makuri at Rising Sun"
    - "Makuri at Tuscan Hills"
    - "Manakau at S.H.1 Bridge"
    - "Manawatu at Apiti Track"
    - "Manawatu at Floodway"
    - "Manawatu at Foxton"
    - "Manawatu at Hopelands"
    - "Manawatu at Moutoa"
    - "Manawatu at Moutoa Gate Pier"
    - "Manawatu at Opiki Bridge"
    - "Manawatu at Opiki Floodway"
    - "Manawatu at Te Ao Nui"
    - "Manawatu at Teachers College"
    - "Manawatu at Upper Gorge"
    - "Manawatu at Victoria Ave"
    - "Manawatu at Weber Road"
    - "Manga-atua at Hopelands Rd"
    - "Mangaehu at Bridge"
    - "Mangaetoroa at Scarrows"
    - "Mangahao at Ballance"
    - "Mangahao at Kakariki"
    - "Mangahao at No. 2 Dam"
    - "Mangaone West at Lees Road"
    - "Mangaone at Awapuni Racecourse"
    - "Mangaone at Bunnythorpe Rd"
    - "Mangaone at Milson Line"
    - "Mangaone at Valley Road"
    - "Mangapapa at Troup Rd"
    - "Mangaroa at Ohura Town Bridge"
    - "Mangatainoka at Hillwood Hukanui"
    - "Mangatainoka at Larsons Road"
    - "Mangatainoka at Pahiatua Dairy Factory"
    - "Mangatainoka at Pahiatua Town Bridge"
    - "Mangatoro at Mangahei Road"
    - "Mangawhero at Aberfeldy"
    - "Mangawhero at Bangonie"
    - "Mangawhero at Ore Ore"
    - "Mangawhero at Ore Ore Slip"
    - "Mangawhero at Pakihi Rd Bridge"
    - "Mangawhero at Raupiu Road"
    - "Mangawhero at SH4 Slip"
    - "Matarawa at City Branch"
    - "Matarawa at Matarawa Valley"
    - "Moawhango at Moawhango"
    - "Mt Maire Repeater"
    - "National Park Climate Station"
    - "Ngahere Park Climate Station"
    - "Ngaruroro Catchment at Ngamatea"
    - "Ohau at Above Makahika Confluence"
    - "Ohau at Estuary"
    - "Ohau at Haines Ford"
    - "Ohau at Makahika"
    - "Ohau at Rongomatane"
    - "Ohura at Nihoniho"
    - "Ohura at Ohura River Road"
    - "Ohura at Tokorima"
    - "Ohura at Waikaka"
    - "Ohura at Waitewhena Airstrip"
    - "Omahine at Moana Trig"
    - "Omaru at Charlies"
    - "Ongarue at Jet Boat Ramp Taumarunui"
    - "Ongarue at Taringamotu"
    - "Oroua at Almadale Slackline"
    - "Oroua at Apiti Gorge Bridge"
    - "Oroua at Awahuri Bridge"
    - "Oroua at Kawa Wool"
    - "Oroua at Kopane Bridge"
    - "Oroua at Rangiotu"
    - "Oroua at Rangiwahia"
    - "Oroua at Te Arakura Road"
    - "Oruakeretaki at S.H.2 Napier"
    - "Owahanga at Branscombe Bridge"
    - "Owahanga at Owahanga Station"
    - "Pakihikura at Pakihikura Airstrip"
    - "Paradise Valley Climate Station"
    - "Patea at Stratford"
    - "Patiki Stream at Kawiu Road"
    - "Pohangina at Alphabet Hut"
    - "Pohangina at Delaware Ridge"
    - "Pohangina at Mais Reach"
    - "Pohangina at Makawakawa Divide"
    - "Pohangina at Piripiri"
    - "Pohangina at Range View Farm"
    - "Pohangina at Ruahine Repeater"
    - "Pohangina at Saddle Road Bridge"
    - "Pohangina at Totara Reserve"
    - "Pohokura Saddle"
    - "Pongaroa at Town"
    - "Porewa Catchment at Tututotara"
    - "Porewa at Dam 62"
    - "Porewa at Dam 73"
    - "Porewa at Dam 75"
    - "Rangitikei at Erewhon Station"
    - "Rangitikei at Hamptons"
    - "Rangitikei at Kakariki"
    - "Rangitikei at Mangaweka"
    - "Rangitikei at McKelvies"
    - "Rangitikei at Onepuhi"
    - "Rangitikei at Pukeokahu"
    - "Rangitikei at Pukeokahu Link"
    - "Raparapawai at Jackson Rd"
    - "Raumai Climate Station"
    - "Retaruke at Link Station"
    - "Ruatiti at Ruatiti Station"
    - "Saddle Road"
    - "Sexton Land Co"
    - "Sluggish Creek at Greenaway Rd"
    - "Tamaki at Hartridges"
    - "Tamaki at Stephensons"
    - "Tamaki at Tamaki Reserve"
    - "Tamaki at Water Supply Weir"
    - "Tapuae at Waituna West"
    - "Tarn Track Climate Station"
    - "Tawataia Dam"
    - "Te Matai Road Aquifer 1"
    - "Te Matai Road Aquifer 2"
    - "Te Matai Road Aquifer 3"
    - "Te Matai Road Aquifer 4"
    - "Te Matai Road Aquifer 6"
    - "Three Kings Climate Station"
    - "Tiraumea at Alfredton"
    - "Tiraumea at Ngaturi"
    - "Tokiahuru at Junction"
    - "Tokiahuru at Karioi Forest"
    - "Tokiahuru at Powells Rd"
    - "Tokomaru at Riverland Farm"
    - "Totara Reserve Water Supply"
    - "Turakina GW"
    - "Turakina at Koeke Airstrip"
    - "Turakina at ONeills Bridge"
    - "Turakina at Otairi"
    - "Turakina at Ruanui"
    - "Turakina at Waipu"
    - "Turitea at Ngahere Park"
    - "Turoa at Repeater"
    - "Tutaenui at Dam E4"
    - "Tutaenui at Dam W3"
    - "Tutaenui at Hammond St"
    - "Tutaenui at Ribby Farm"
    - "Upper Mangahao at No.1 Dam"
    - "Waiharuru at S.H.49"
    - "Waihi at S.H.52"
    - "Waikawa at North Manakau Road"
    - "Waikawa at ds Manakau Confluence"
    - "Waimarino Forest Climate Station"
    - "Wainui at Herbertville"
    - "Wainui at Herbertville Road Br"
    - "Waitangi at Tangiwai"
    - "Waitarere"
    - "Waitotara at Rimunui Station"
    - "Westlawn Climate Station"
    - "Whangaehu at Aranui"
    - "Whangaehu at Karioi"
    - "Whangaehu at Karioi Pulpmill"
    - "Whangaehu at Kauangaroa"
    - "Whangaehu at Kowhai St Mangamahu"
    - "Whangaehu at Tangiwai Flood Gauge"
    - "Whangaehu at Tangiwai SH49 Bridge"
    - "Whangaehu at Titoki"
    - "Whangaehu at Tukino"
    - "Whangaehu at Tukino Repeater"
    - "Whangamomona at Bridge to Somewhere"
    - "Whangamomona at Marco Road"
    - "Whanganui at Cherry Grove"
    - "Whanganui at Kirikau"
    - "Whanganui at Mataimona Trig"
    - "Whanganui at Pipiriki"
    - "Whanganui at Piriaka"
    - "Whanganui at Piriaka Notch"
    - "Whanganui at Te Maire"
    - "Whanganui at Te Porere"
    - "Whanganui at Te Rewa"
    - "Whanganui at Town Bridge"
    - "Whelans at Kane Boundary"
    - "Whitebait Creek at Edinburgh Terrace"


measurements:
    - Air Temperature (1.5m)
