# Hilltop Server Configuration
base_url: "http://hilltopdev.horizons.govt.nz/"
hts: "boo.hts"
export_file: "output_dump/missing.csv"
start: "2024-02-01 00:00"
end: "2024-03-01 00:00"

sites:
    - Manawatu at Teachers College
    - Mangapapa at Troup Rd
    - Akitio at Cadmus Bridge
    - Arawhata Drain at Dairy Track Bridge
    - Arawhata Drain at Hokio Beach Road
    - Butlers
    - Air Quality at Taihape


measurements:
    - DO Saturation [Dissolved Oxygen (%)]
    - Soil Moisture [Soil Moisture]
    - Water Temperature [Dissolved Oxygen sensor]
    - Water Temperature [Water Temperature]
    - Air Temperature (1.5m)
