# Hilltop Server Configuration
base_url: "http://hilltopdev.horizons.govt.nz/"
hts: "boo.hts"
export_file: "output_dump/missing.csv"
start: "2024-04-01 00:00"
end: "2024-05-01 00:00"

Lakes:
    - Hokio at Lake Horowhenua
    - Lake Dudding
    - Lake Heaton
    - Lake Herbert
    - Lake Horowhenua at Buoy
    - Lake Horowhenua at Weir
    - Lake Kaitoke or other
    - Lake Kohata
    - Lake Koitiata
    - Lake Papaitonga at Staff Gauge
    - Lake Pauri
    - Lake Waipu or other
    - Lake William
    - Lake Wiritoa
