# Hilltop Server Configuration
base_url: "http://hilltopdev.horizons.govt.nz/"
standard_hts_filename: "RawLoggerNet.hts"
check_hts_filename: "HydrobotCheckData.hts"

# Data Source Configuration
site: "Manawatu at Teachers College"
# standard_measurement_name: "DO Saturation"
standard_measurement_name: "DO Saturation [Dissolved Oxygen (%)]"
check_measurement_name: "DO saturation check"
frequency: "15min"

# Processing Configuration
from_date: "2021-12-21 11:15"
to_date: "2024-04-02 10:00"
defaults:
  delta: 5
  gap_limit: 12
  high_clip: 200
  low_clip: 50
  max_qc: 600
  span: 10

# Annalist Configuration
analyst_name: "default"
logfile: "hydrobot_logs.csv"
format:
  file: "%(asctime)s, %(analyst_name)s, %(function_name)s, %(site)s, %(measurement)s, %(from_date)s, %(to_date)s, %(message)s"
  stream: ""

inspection_expiry:
    500:
        months: 2
    0:
        months: 4

constant_check_shift: 0
